# Site settings
course_name: Deep Learning
course_description: "Starting from an artificial neuron model, the aim of this course is to understand feed forward and recurrent architectures 
of Artificial Neural Networks, all the way to the modern Deep Neural Networks. Specifically, we will discuss the basic Neuron models (McCulloch Pitts, Perceptron),
Multi-Layer Perceptron (MLP), Convolutional Neural Networks (CNN), and Recurrent Neural Networks (RNN) (LSTM and GRU). We will understand the representational 
ability of these models along with how to train them using the Gradient Descent technique using the Backpropagation algorithm. Specifically, we will discuss 
various optimization algorithms such as Nesterov Accelerated Gradient Descent, Adam, AdaGrad and RMSProp, etc. Towards the end, students of this course get 
exposed to important deep learning frameworks from computer vision and Natural Language Processing such as encoder-decoder architecture, attention mechanism, etc."
course_semester: "Jan-May 2023"

baseurl: "/dl" # the subpath of your site, e.g. /blog/
url: "http://krmopuri.github.io/" # the base hostname & protocol for your site

schoolname: "Dept. of AI, IITH"
schoolurl: "https://ai.iith.ac.in/"
#twitter_username: username 

address: |
    Department of Artificial Intelligence
    IIT Hyderabad, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
